---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: acm-clusterlifecycle-placement-binding
  namespace: policies
placementRef:
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
  name: acm-clusterlifecycle-placement
subjects:
- apiGroup: policy.open-cluster-management.io
  kind: Policy
  name: acmc-lusterlifecycle
