apiVersion: policy.open-cluster-management.io/v1
kind: CertificatePolicy
metadata:
  name: certs-check
  namespace: policies
spec:
  namespaceSelector:
    include:
      - openshift-ingress
      - openshift-config
  labelSelector:
    certificate-type: apiserver
  remediationAction: inform
  severity: high
  minimumDuration: 600h
