apiVersion: v1
kind: ConfigMap
metadata:
  name: local-storage-operator-init
  namespace: policies
data:
  channel: {{ .Values.subscription.channel }}
  startingCSV: {{ .Values.subscription.startingCSV }}
