apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  annotations:
    policy.open-cluster-management.io/categories: CM Configuration Management
    policy.open-cluster-management.io/controls: CM-2 Baseline Configuration
    policy.open-cluster-management.io/standards: NIST SP 800-53
    policy.open-cluster-management.io/description: Loki Operator Installation
  name: loki-operator-install
  namespace: policies
spec:
  disabled: true
  policy-templates:
#Create namespace
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: loki-namespace
      spec:
        pruneObjectBehavior: None
        remediationAction: enforce
        severity: high
        object-templates:
        - complianceType: musthave
          objectDefinition:
            apiVersion: v1
            kind: Namespace
            metadata:
              labels:
                 openshift.io/cluster-monitoring: "true"
              name: openshift-operators-redhat
#Create the operator group
  - extraDependencies:
     - apiVersion: policy.open-cluster-management.io/v1
       kind: ConfigurationPolicy
       name: loki-namespace
       namespace: ""
       compliance: Compliant
    objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: loki-operator-group
      spec:
        pruneObjectBehavior: None
        remediationAction: enforce
        severity: high
        object-templates:
        - complianceType: musthave
          objectDefinition:
            apiVersion: operators.coreos.com/v1
            kind: OperatorGroup
            metadata:
              name: loki-operator-group
              namespace: openshift-operators-redhat
            spec:
              upgradeStrategy: Default
#Create the subscription when the operator group is ready
  - extraDependencies:
     - apiVersion: policy.open-cluster-management.io/v1
       kind: ConfigurationPolicy
       name: loki-operator-group
       namespace: ""
       compliance: Compliant
    objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: loki-subscription
      spec:
        pruneObjectBehavior: None
        remediationAction: enforce
        severity: high
        object-templates:
        - complianceType: musthave
          objectDefinition:
            apiVersion: operators.coreos.com/v1alpha1
            kind: Subscription
            metadata:
              name: loki-operator
              namespace: openshift-operators-redhat
            spec:
              channel: '{{hub fromConfigMap "policies" "loki-operator-init" "channel" hub}}'
              installPlanApproval: Manual
              name: loki-operator
              source: redhat-operators
              sourceNamespace: openshift-marketplace
              startingCSV: '{{hub fromConfigMap "policies" "loki-operator-init" "startingCSV" hub}}'
#Approve the Install plan when it has been detected
  - extraDependencies:
     - apiVersion: policy.open-cluster-management.io/v1
       kind: ConfigurationPolicy
       name: loki-subscription
       namespace: ""
       compliance: Compliant
    objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: loki-operator-installplan-approve
      spec:
        pruneObjectBehavior: None
        remediationAction: enforce
        severity: high
        object-templates-raw: |
          {{- range $installplan := (lookup "operators.coreos.com/v1alpha1" "InstallPlan" "openshift-operators-redhat" "").items }}
            {{- range $installplan.spec.clusterServiceVersionNames }}
            {{- if eq . "{{hub fromConfigMap "policies" "loki-operator-init" "startingCSV" hub}}" }}
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1alpha1
                kind: InstallPlan
                metadata:
                  namespace: openshift-operators-redhat
                  name: '{{ $installplan.metadata.name }}'
                spec:
                  approved: true
            {{- end }}
            {{- end }}
          {{- end }}
#Check the CSV
  - extraDependencies:
     - apiVersion: policy.open-cluster-management.io/v1
       kind: ConfigurationPolicy
       name: loki-subscription
       namespace: ""
       compliance: Compliant
    objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: loki-operator-csv-check
      spec:
        pruneObjectBehavior: None
        remediationAction: inform
        severity: high
        object-templates:
        - complianceType: musthave
          objectDefinition:
            apiVersion: operators.coreos.com/v1alpha1
            kind: ClusterServiceVersion
            metadata:
              name: '{{hub fromConfigMap "policies" "loki-operator-init" "startingCSV" hub}}'
              namespace: openshift-operators-redhat
            status:
              phase: Succeeded 
