---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: local-storage-placementbinding
  namespace: policies
placementRef:
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
  name: local-storage-placement
subjects:
- apiGroup: policy.open-cluster-management.io
  kind: Policy
  name: local-storage-operator-install
